### PR TITLE
Serializing unparented HTML node on JRuby

### LINKED ISSUE #2559: [bug] jruby NPE when serializing an unparented HTML node
**Please describe the bug**

```ruby
Nokogiri::HTML::Document.parse("<div></div>").create_text_node("asdf").to_s
```

results in

```
Unhandled Java exception: java.lang.NullPointerException
java.lang.NullPointerException: null
      isHtmlScript at nokogiri/internals/SaveContextVisitor.java:812
             enter at nokogiri/internals/SaveContextVisitor.java:833
            accept at nokogiri/XmlText.java:75
   native_write_to at nokogiri/XmlNode.java:1352
              call at nokogiri/XmlNode$INVOKER$i$1$0$native_write_to.gen:-1
              call at org/jruby/internal/runtime/methods/JavaMethod.java:846
      cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:329
              call at org/jruby/runtime/callsite/CachingCallSite.java:87
```

**Expected behavior**

Unparented nodes should serialize normally, as they do in the CRuby implementation

### PR DESCRIPTION
**Pull request by cbasguti**
**What problem is this PR intended to solve?**

Closes #2559

This PR aims to solve issue #2559 in the Nokogiri project. After investigating the reported bug, it was identified that a NullPointerException occurs in the isHtmlScript and isHtmlStyle functions due to the inability to evaluate a null object in Java. The proposed solution involves adding a null check for the getParentNode() method's return value and logging an appropriate message if the parent node is null or does not match the expected tag name. A draft PR will be opened to implement these modifications and gather feedback for effectiveness.

**Have you included adequate test coverage?**

As this is my first contribution to the project, I am uncertain about the appropriate location to include the corresponding test. However, I am committed to ensuring adequate test coverage for this change and will collaborate with the project team to determine the best approach.

**Does this change affect the behavior of either the C or the Java implementations?**

This change only affects the Java implementation, as the issue of a NullPointerException is specific to that platform. The C implementation does not encounter this problem.

### CODE REVIEW

**Comment by flavorjones** [comment]
@cbasguti Thank you for opening this PR! I've kicked off CI, I'd like to see what the test suite says before reviewing.

**Comment by flavorjones** [comment]
Also, if you didn't see it, I tried to provide some help for initial contributions here: https://nokogiri.org/CONTRIBUTING.html#submitting-pull-requests

Thank you again!

**Comment by cbasguti** [comment]
Ok, I took another look at the contribution documentation page, included a test following your instructions, and also formatted it as needed. Thank you very much for your patience and I look forward to your comments.

**Comment by flavorjones** [comment]
Don't worry about the one failing test "ci / bsd", it's flaky. This looks all green, will review over the weekend!

File: ext/java/nokogiri/internals/SaveContextVisitor.java [hunk 1]
```diff
@@ -810,15 +810,28 @@ public int compare(Attr attr0, Attr attr1) {
   private boolean
   isHtmlScript(Text text)
   {
-    return htmlDoc && text.getParentNode().getNodeName().equals("script");
+    Node parentNode = text.getParentNode();
+    if (parentNode != null && parentNode.getNodeName().equals("script")) {
+      return htmlDoc;
+    } else {
+      System.out.println("getParentNode() returned null or parent node is not 'script'.");
```
Comment (flavorjones) [inline ext/java/nokogiri/internals/SaveContextVisitor.java:817]: We shouldn't emit a message, we should just match the C extension's behavior.

File: ext/java/nokogiri/internals/SaveContextVisitor.java [hunk 2]
```diff
@@ -810,15 +810,28 @@ public int compare(Attr attr0, Attr attr1) {
...
 
   private boolean
   isHtmlStyle(Text text)
   {
-    return htmlDoc && text.getParentNode().getNodeName().equals("style");
+    Node parentNode = text.getParentNode();
+    if (parentNode != null && parentNode.getNodeName().equals("style")) {
+      return htmlDoc;
+    } else {
+      System.out.println("getParentNode() returned null or parent node is not 'style'.");
```
Comment (flavorjones) [inline ext/java/nokogiri/internals/SaveContextVisitor.java:829]: We shouldn't emit a message, we should just match the C extension's behavior.

**Review by flavorjones — CHANGES_REQUESTED** [review]
Looking at how these (private) functions are used, I think the missing abstraction is "isCDATA", which should return true if the parent node name is "script" or "style".

Can you merge these two functions into one, `isCDATA()`? I think you can probably have it return a boolean value something like

```
return htmlDoc && parentNode != null && (parentNode.getNodeName().equals("style") || parentNode.getNodeName().equals("script"))
```

**Comment by flavorjones** [comment]
Looks good! I think this will go green, and I'll merge it. I've credited you in the CHANGELOG!

Thank you so much for your contribution!

**Comment by flavorjones** [comment]
Available in [Release 1.15.3 / 2023-07-05 · sparklemotion/nokogiri](https://github.com/sparklemotion/nokogiri/releases/tag/v1.15.3)
